# services:
#   backend:
#     image: unstableme02/ishani_dms-backend:latest
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend/uploads:/app/uploads
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     environment:
#       - DATABASE_URL=postgresql+psycopg2://postgres:root@db:5432/ocr_db
#     restart: always

#   frontend:
#     image: unstableme02/ishani_dms-frontend:latest
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     restart: always



services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?database user required}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?database password required}
      - POSTGRES_DB=${POSTGRES_DB:?database name required}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: unstableme02/ishani_dms-backend:latest
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:?database url required}
    depends_on:
      - db
    restart: always

  frontend:
    image: unstableme02/ishani_dms-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: